version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
